CROP_VALUE_TO_COMMODITY = {
    "1": "CORN",
    "2": "COTTON",
    "3": "RICE",
    "4": "SORGHUM",
    "5": "SOYBEANS",
    "6": "SUNFLOWER",
    "10": "PEANUTS",
    "11": "TOBACCO",
    "12": "SWEET CORN",
    "13": "POP OR ORN CORN",
    "14": "MINT",
    "21": "BARLEY",
    "22": "WHEAT_DURUM",
    "23": "WHEAT_SPRING",
    "24": "WHEAT_WINTER",
    "25": "OTHER SMALL GRAINS",
    "26": "DBL CROP WINWHT/SOYBEANS",
    "27": "RYE",
    "28": "OATS",
    "29": "MILLET",
    "30": "SPELTZ",
    "31": "CANOLA",
    "32": "FLAXSEED",
    "33": "SAFFLOWER",
    "34": "RAPE SEED",
    "35": "MUSTARD",
    "36": "ALFALFA",
    "37": "OTHER HAY/NON ALFALFA",
    "38": "CAMELINA",
    "39": "BUCKWHEAT",
    "41": "SUGARBEETS",
    "42": "DRY BEANS",
    "43": "POTATOES",
    "44": "OTHER CROPS",
    "45": "SUGARCANE",
    "46": "SWEET POTATOES",
    "47": "MISC VEGS & FRUITS",
    "48": "WATERMELONS",
    "49": "ONIONS",
    "50": "CUCUMBERS",
    "51": "CHICK PEAS",
    "52": "LENTILS",
    "53": "PEAS",
    "54": "TOMATOES",
    "55": "CANEBERRIES",
    "56": "HOPS",
    "57": "HERBS",
    "58": "CLOVER/WILDFLOWERS",
    "59": "SOD/GRASS SEED",
    "60": "SWITCHGRASS",
}

COMMODITY_TO_CROP_VALUE = {v: int(k) for k, v in CROP_VALUE_TO_COMMODITY.items()}