########################################################################################################################
# this contains all the API keys to obtain data.
[api]
USDA_api_key = "7BACC84D-4D4E-31CE-9828-0EAF5D6338DB"
NCDC_api_key = "sAfDxhRkTzDkPBjtktOThBJjnCfzAtax"

########################################################################################################################
# this contains the standard setup of model training
[train]
train_start_date = "2014-01-01"
valid_start_date = "2024-01-01"

########################################################################################################################
# this contains all the path information. All pathes are relative to this config.toml document.
# The project root is set to be ../
[path]
project_root = '../'

########################################################################################################################
# The update_data function will update the data listed here
# Please also implement their filtering rule, and contract specification in the next two sections
[data]
# Market data
# SRW wheat, HRW wheat, corn, soybean, soyoil, soymeal, sugar 11, orange juice.
symbols = ['ZW=F', 'KE=F', 'ZC=F', 'ZS=F', 'ZL=F', 'ZM=F', 'SB=F', 'OJ=F']
# This is the default starting date of the market data
start_date_default = "2014-01-01"

# USDA reports
commodities = [
    'WHEAT_TOTAL', 'WHEAT_WINTER', 'WHEAT_SRW', 'WHEAT_HRW', 'WHEAT_SPRING', 'WHEAT_DURUM',
    'CORN',
    'SOYBEANS',
    'SUGARBEETS', 'SUGARCANE',
    'ORANGES_VALENCIA']
reports = ['production', 'stocks', 'condition']
levels = ['national', 'state']
# This is the default start year of the USDA reports
start_year_default = 2014

# Weather data
# Please check the corp name in src/constants/crop_codes.py
crops = [
    'WHEAT_WINTER', 'WHEAT_SPRING', 'WHEAT_DURUM',
    'CORN',
    'SOYBEANS',
    'SUGARBEETS', 'SUGARCANE',
]

# The cdl should be downloaded from https://www.nass.usda.gov/Research_and_Science/Cropland/Release/
raw_cdl_path = "../dataset/raw/2024_30m_cdls.tif"

downscale_factor = 30

########################################################################################################################
# The following are filtering rule for getting data from USDA quickstats API

# WHEAT TOTAL - Production Report
[usda_data.WHEAT_TOTAL.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = "ALL CLASSES"
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_TOTAL.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']


[usda_data.WHEAT_TOTAL.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = "ALL CLASSES"
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_TOTAL.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']

#########################################################################

# WHEAT TOTAL - Stocks Report
[usda_data.WHEAT_TOTAL.stocks.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'STOCKS'
commodity_desc = 'WHEAT'
class_desc = "ALL CLASSES"
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_TOTAL.stocks.national]
columns = ['load_time', 'year', 'end_code', 'Value', 'unit_desc','source_desc', 'short_desc']

[usda_data.WHEAT_TOTAL.stocks.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'STOCKS'
commodity_desc = 'WHEAT'
class_desc = "ALL CLASSES"
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_TOTAL.stocks.state]
columns = ['state_name', 'load_time', 'year', 'end_code', 'Value', 'unit_desc','source_desc', 'short_desc']

#########################################################################

# WHEAT WINTER - Production report
[usda_data.WHEAT_WINTER.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'WINTER'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_WINTER.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']

[usda_data.WHEAT_WINTER.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'WINTER'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_WINTER.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']

#########################################################################

# WHEAT WINTER - Condition report
[usda_data.WHEAT_WINTER.condition.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'CONDITION'
commodity_desc = 'WHEAT'
class_desc = 'WINTER'
source_desc = "SURVEY"

[usda_data.WHEAT_WINTER.condition.national]
columns = ['load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']


[usda_data.WHEAT_WINTER.condition.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'CONDITION'
commodity_desc = 'WHEAT'
class_desc = 'WINTER'
source_desc = "SURVEY"

[usda_data.WHEAT_WINTER.condition.state]
columns = ['state_name', 'load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']
#########################################################################

# WHEAT SRW - Production report
[usda_data.WHEAT_SRW.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'WINTER, RED, SOFT'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_SRW.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']

[usda_data.WHEAT_SRW.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'WINTER, RED, SOFT'
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_SRW.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']

#########################################################################

# WHEAT HRW - Production report
[usda_data.WHEAT_HRW.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'WINTER, RED, HARD'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_HRW.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']

[usda_data.WHEAT_HRW.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'WINTER, RED, HARD'
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_HRW.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']

#########################################################################

# WHEAT SPRING - production report
[usda_data.WHEAT_SPRING.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'SPRING, (EXCL DURUM)'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_SPRING.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']


[usda_data.WHEAT_SPRING.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'SPRING, (EXCL DURUM)'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_SPRING.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']


#########################################################################

# WHEAT SPRING - Condition report
[usda_data.WHEAT_SPRING.condition.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'CONDITION'
commodity_desc = 'WHEAT'
class_desc = 'SPRING, (EXCL DURUM)'
source_desc = "SURVEY"

[usda_data.WHEAT_SPRING.condition.national]
columns = ['load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']


[usda_data.WHEAT_SPRING.condition.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'CONDITION'
commodity_desc = 'WHEAT'
class_desc = 'SPRING, (EXCL DURUM)'
source_desc = "SURVEY"

[usda_data.WHEAT_SPRING.condition.state]
columns = ['state_name', 'load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']
#########################################################################

# WHEAT DURUM - production report
[usda_data.WHEAT_DURUM.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'SPRING, DURUM'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_DURUM.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']

[usda_data.WHEAT_DURUM.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'WHEAT'
class_desc = 'SPRING, DURUM'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.WHEAT_DURUM.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']


#########################################################################

# CORN - production report
[usda_data.CORN.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.CORN.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']

[usda_data.CORN.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.CORN.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']

#########################################################################

# CORN - stocks report
[usda_data.CORN.stocks.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'STOCKS'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.CORN.stocks.national]
columns = ['load_time', 'year', 'end_code', 'Value', 'unit_desc','source_desc', 'short_desc']


[usda_data.CORN.stocks.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'STOCKS'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.CORN.stocks.state]
columns = ['state_name', 'load_time', 'year', 'end_code', 'Value', 'unit_desc','source_desc', 'short_desc']
#########################################################################

# CORN - Condition report
[usda_data.CORN.condition.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'CONDITION'
source_desc = "SURVEY"

[usda_data.CORN.condition.national]
columns = ['load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']

[usda_data.CORN.condition.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'CONDITION'
source_desc = "SURVEY"

[usda_data.CORN.condition.state]
columns = ['state_name', 'load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']

#########################################################################

# SOYBEANS - production report
[usda_data.SOYBEANS.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.SOYBEANS.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']


[usda_data.SOYBEANS.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.SOYBEANS.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']

#########################################################################

# SOYBEANS - stocks report
[usda_data.SOYBEANS.stocks.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'STOCKS'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.SOYBEANS.stocks.national]
columns = ['load_time', 'year', 'end_code', 'Value', 'unit_desc','source_desc', 'short_desc']


[usda_data.SOYBEANS.stocks.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'STOCKS'
unit_desc = "BU"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.SOYBEANS.stocks.state]
columns = ['state_name', 'load_time', 'year', 'end_code', 'Value', 'unit_desc','source_desc', 'short_desc']

#########################################################################

# SOYBEANS - Condition report
[usda_data.SOYBEANS.condition.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'CONDITION'
source_desc = "SURVEY"

[usda_data.SOYBEANS.condition.national]
columns = ['load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']


[usda_data.SOYBEANS.condition.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'CONDITION'
source_desc = "SURVEY"

[usda_data.SOYBEANS.condition.state]
columns = ['state_name', 'load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']

#########################################################################

# SUGARBEETS - production report
[usda_data.SUGARBEETS.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
unit_desc = "TONS"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.SUGARBEETS.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']

[usda_data.SUGARBEETS.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
unit_desc = "TONS"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.SUGARBEETS.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']

#########################################################################

# SUGARBEETS - Condition report
[usda_data.SUGARBEETS.condition.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'CONDITION'
source_desc = "SURVEY"

[usda_data.SUGARBEETS.condition.state]
columns = ['state_name', 'load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']

#########################################################################

# SUGARCANE - production report
[usda_data.SUGARCANE.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
util_practice_desc = 'SUGAR & SEED'
unit_desc = "TONS"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.SUGARCANE.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']

[usda_data.SUGARCANE.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
util_practice_desc = 'SUGAR & SEED'
unit_desc = "TONS"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.SUGARCANE.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc','reference_period_desc','source_desc', 'short_desc']

#########################################################################

# SUGARCANE - Condition report
[usda_data.SUGARCANE.condition.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'CONDITION'
source_desc = "SURVEY"

[usda_data.SUGARCANE.condition.state]
columns = ['state_name', 'load_time', 'year', 'week_ending', 'Value', 'unit_desc','source_desc', 'short_desc']

#########################################################################

# ORANGES_VALENCIA - production report
[usda_data.ORANGES_VALENCIA.production.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'ORANGES'
class_desc = 'VALENCIA'
util_practice_desc = 'PROCESSING'
unit_desc = "TONS"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.ORANGES_VALENCIA.production.national]
columns = ['load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']


[usda_data.ORANGES_VALENCIA.production.state.filters]
agg_level_desc = "STATE"
statisticcat_desc = 'PRODUCTION'
commodity_desc = 'ORANGES'
class_desc = 'VALENCIA'
util_practice_desc = 'PROCESSING'
unit_desc = "TONS"
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.ORANGES_VALENCIA.production.state]
columns = ['state_name', 'load_time', 'year', 'Value', 'unit_desc', 'reference_period_desc','source_desc', 'short_desc']

#########################################################################

# ORANGES_VALENCIA - stocks report
[usda_data.ORANGES_VALENCIA.stocks.national.filters]
agg_level_desc = "NATIONAL"
statisticcat_desc = 'STOCKS'
commodity_desc = 'ORANGES'
domain_desc = "TOTAL"
source_desc = "SURVEY"

[usda_data.ORANGES_VALENCIA.stocks.national]
columns = ['load_time', 'year', 'end_code', 'Value', 'unit_desc','source_desc', 'short_desc']

########################################################################################################################
# The following are contract rules for each symbol
# For new rules other than the rule here, please implement it at src/data/preprocess.py
[contracts.ZW]
months = [3, 5, 7, 9, 12]
rule = "before_15th"

[contracts.KE]
months = [3, 5, 7, 9, 12]
rule = "before_15th"

[contracts.ZC]
months = [3, 5, 7, 9, 12]
rule = "before_15th"

[contracts.ZS]
months = [1, 3, 5, 7, 8, 9, 11]
rule = "before_15th"

[contracts.ZL]
months = [1, 3, 5, 7, 8, 9, 10, 12]
rule = "before_15th"

[contracts.ZM]
months = [1, 3, 5, 7, 8, 9, 10, 12]
rule = "before_15th"

[contracts.SB]
months = [3, 5, 7, 10]
rule = "last_business_day"

[contracts.OJ]
months = [1, 3, 5, 7, 9, 11]
rule = "before_15th"